name: ItemPredicateParser
main: me.blvckbytes.item_predicate_parser.ItemPredicateParserPlugin
version: 0.0.7
author: BlvckBytes
api-version: 1.13
softdepend: [EcoEnchants]
commands:
  itempredicateparser:
    aliases: [ipp]
permissions:
  itempredicateparser.command.ipp.reload:
    description: 'Invoke the reload command'
    default: op
  itempredicateparser.command.ipp.test:
    description: 'Invoke the test command'
    default: op